### PR TITLE
add support for EL8

### PR DESCRIPTION
**Pull request by vchepkov**
- dnf doesn't support makecache fast command, clean expire-cache is an equivalent and available on both, EL7 and EL8

### CODE REVIEW

**Comment by nmaludy** [comment]
@vchepkov This looks great from a code inspection standpoint! Still waiting on the CentOS 8 Vagrant box to come available so i can test it out.

Sorry for the delay, just wanted to let you know i haven't forgotten about this.

Thanks so much for the contribution!

**Comment by vchepkov** [comment]
NP, I am using this one https://app.vagrantup.com/generic/boxes/centos8

**Comment by vchepkov** [comment]
Interesting, you merged your master into my branch in my fork. I didn't know you are allowed to do it. Probably by mistake?

**Comment by nmaludy** [comment]
I was fixing a merge conflict you had in the README file. Did it via GitHub.

**Comment by nmaludy** [comment]
When you get a chance, could you please add a changelog entry in the Development section please?

**Comment by vchepkov** [comment]
I have rebased on master and added the Changelog entry.

**Comment by nmaludy** [comment]
Just tested and everything worked great! I'll put a release together this morning.

THANK  YOU again for the contribution!!!

**Pull request merged**
