### PR TITLE
hotfix/prom-https

### PR DESCRIPTION
**Pull request by asktheaxis**
switching prom urls to https

### CODE REVIEW

**Comment by asktheaxis** [comment]
@bishopbm1 @jschoewe

**Comment by jschoewe** [comment]
LGTM can't merge though

**Comment by bishopbm1** [comment]
We need to iterate the version in the metadata and changelog.

**Comment by bishopbm1** [comment]
Update changelog and iterate metadata version

**Review by bishopbm1 — APPROVED** [review]
LGTM

**Pull request merged**
